[package]
name = "countryfetch"
version = "0.2.0"
edition = "2024"
repository = "https://github.com/nik-rev/countryfetch"
homepage = "https://github.com/nik-rev/countryfetch"
description = "A Command-line tool similar to Neofetch for obtaining information about your country"
license = "MIT OR Apache-2.0"

[lib]
name = "countryfetch"
path = "src/lib.rs"

[[bin]]
name = "countryfetch"
path = "src/main.rs"

[dependencies]
public-ip = "0.2"
tokio = { version = "1.43", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", default-features = false, features = [
  "json",
  "native-tls",
] }
# PNG -> ASCII
rascii_art = "0.4.5"
# NOTE: This must be the same version as what is required by `rascii_art`
image = "0.24.9"
separator = "0.3"
# colored strings
colored = "3.0"
clap = { version = "4.5", features = [
  "derive",
  "wrap_help",
  "unstable-markdown",
] }
anstyle = "1.0"
directories = "6.0"

textwrap = "0.16"

openssl = { version = "0.10", features = ["vendored"] }

[workspace]
members = [".", "generate_country_data"]
default-members = ["."]
resolver = "1"

[workspace.package]
repository = "https://github.com/nik-rev/countryfetch"

[workspace.lints.clippy]
pedantic = { priority = -1, level = "warn" }
nursery = { priority = -1, level = "warn" }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
codegen-units = 1
lto = true
