[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
# SVG -> PNG
resvg = "0.45"
# PNG -> ASCII
rascii_art = "0.4.5"

# NOTE: This must be the same version as what is required by `rascii_art`
image = "0.24.9"
tiny-skia = "0.11"
