[package]
name = "gen_country"
version = "0.2.0"
edition = "2024"
license = "MIT"
description = "Includes information about countries"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
